// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TestSedona.Data;

namespace TestSedona.Migrations
{
    [DbContext(typeof(SedonaContext))]
    [Migration("20220209163245_init")]
    partial class init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.11")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("TestSedona.Entities.DetaliiFactura", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<decimal>("Cantitate")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("IdFactura")
                        .HasColumnType("int");

                    b.Property<int>("IdProdus")
                        .HasColumnType("int");

                    b.Property<decimal>("Pret")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id")
                        .IsClustered(false);

                    b.HasIndex("IdFactura");

                    b.HasIndex("IdProdus");

                    b.ToTable("DetaliiFactura");
                });

            modelBuilder.Entity("TestSedona.Entities.Factura", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Data")
                        .HasColumnType("datetime2");

                    b.Property<string>("NrFactura")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Tva")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ValoareCuTva")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ValoareFaraTVA")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id")
                        .IsClustered(false);

                    b.ToTable("Factura");
                });

            modelBuilder.Entity("TestSedona.Entities.Produs", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Denumire")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Pret")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id")
                        .IsClustered(false);

                    b.ToTable("Produs");
                });

            modelBuilder.Entity("TestSedona.Entities.DetaliiFactura", b =>
                {
                    b.HasOne("TestSedona.Entities.Factura", "Factura")
                        .WithMany("DetaliiFactura")
                        .HasForeignKey("IdFactura")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TestSedona.Entities.Produs", "Produs")
                        .WithMany("DetaliiFactura")
                        .HasForeignKey("IdProdus")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Factura");

                    b.Navigation("Produs");
                });

            modelBuilder.Entity("TestSedona.Entities.Factura", b =>
                {
                    b.Navigation("DetaliiFactura");
                });

            modelBuilder.Entity("TestSedona.Entities.Produs", b =>
                {
                    b.Navigation("DetaliiFactura");
                });
#pragma warning restore 612, 618
        }
    }
}
